// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnectedNode(arg1, arg2) {
  return window['go']['controller']['App']['AddConnectedNode'](arg1, arg2);
}

export function AddDirectoriesFromDialog() {
  return window['go']['controller']['App']['AddDirectoriesFromDialog']();
}

export function AddLink(arg1) {
  return window['go']['controller']['App']['AddLink'](arg1);
}

export function AddLooseFilesFromDialog() {
  return window['go']['controller']['App']['AddLooseFilesFromDialog']();
}

export function AddNode(arg1, arg2, arg3) {
  return window['go']['controller']['App']['AddNode'](arg1, arg2, arg3);
}

export function ClearFileList() {
  return window['go']['controller']['App']['ClearFileList']();
}

export function ClearTree() {
  return window['go']['controller']['App']['ClearTree']();
}

export function GetFileList() {
  return window['go']['controller']['App']['GetFileList']();
}

export function GetNodeCategories() {
  return window['go']['controller']['App']['GetNodeCategories']();
}

export function GetPresetNames() {
  return window['go']['controller']['App']['GetPresetNames']();
}

export function GetTree() {
  return window['go']['controller']['App']['GetTree']();
}

export function LoadFile() {
  return window['go']['controller']['App']['LoadFile']();
}

export function ParseTree() {
  return window['go']['controller']['App']['ParseTree']();
}

export function ParseTreePreview() {
  return window['go']['controller']['App']['ParseTreePreview']();
}

export function RemoveDirectory(arg1) {
  return window['go']['controller']['App']['RemoveDirectory'](arg1);
}

export function RemoveLink(arg1) {
  return window['go']['controller']['App']['RemoveLink'](arg1);
}

export function RemoveLooseFile(arg1) {
  return window['go']['controller']['App']['RemoveLooseFile'](arg1);
}

export function RemoveNode(arg1) {
  return window['go']['controller']['App']['RemoveNode'](arg1);
}

export function Save(arg1) {
  return window['go']['controller']['App']['Save'](arg1);
}

export function SaveAs() {
  return window['go']['controller']['App']['SaveAs']();
}

export function UpdateInputDefaultValue(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['App']['UpdateInputDefaultValue'](arg1, arg2, arg3, arg4);
}

export function UpdateNodePosition(arg1, arg2, arg3) {
  return window['go']['controller']['App']['UpdateNodePosition'](arg1, arg2, arg3);
}

export function UpdateUption(arg1, arg2, arg3) {
  return window['go']['controller']['App']['UpdateUption'](arg1, arg2, arg3);
}
