// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function GetTestTree():Promise<core.SerializableTree>;

export function Greet(arg1:string):Promise<string>;

export function ParseTree():Promise<Array<string>>;

export function UpdateInputDefaultValue(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;
