// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLink(arg1) {
  return window['go']['controller']['App']['AddLink'](arg1);
}

export function AddNode(arg1, arg2, arg3) {
  return window['go']['controller']['App']['AddNode'](arg1, arg2, arg3);
}

export function ClearTree() {
  return window['go']['controller']['App']['ClearTree']();
}

export function GetNodeCategories() {
  return window['go']['controller']['App']['GetNodeCategories']();
}

export function GetTestTree() {
  return window['go']['controller']['App']['GetTestTree']();
}

export function ParseTree() {
  return window['go']['controller']['App']['ParseTree']();
}

export function SetContext(arg1) {
  return window['go']['controller']['App']['SetContext'](arg1);
}

export function UpdateInputDefaultValue(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['App']['UpdateInputDefaultValue'](arg1, arg2, arg3, arg4);
}

export function UpdateNodePosition(arg1, arg2, arg3) {
  return window['go']['controller']['App']['UpdateNodePosition'](arg1, arg2, arg3);
}
