// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTestTree() {
  return window['go']['controller']['App']['GetTestTree']();
}

export function Greet(arg1) {
  return window['go']['controller']['App']['Greet'](arg1);
}

export function ParseTree() {
  return window['go']['controller']['App']['ParseTree']();
}

export function UpdateInputDefaultValue(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['App']['UpdateInputDefaultValue'](arg1, arg2, arg3, arg4);
}
